// This file is automatically generated. Do not modify it manually.
// To regenerate this file, ask the agent to "update my firebase config".
// For more details, see the 'Firebase Usage Instructions' in the 'Guidelines' section.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-8029784041-8d4c8',
  appId: '1:793868989809:web:be2e9daa25088a7f6572d0',
  apiKey: 'AIzaSyB3dhwwvoaxkz_RQzBJlL-RovnFu8RTYJc',
  authDomain: 'studio-8029784041-8d4c8.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '793868989809',
};
